#!/usr/bin/python

import sys
import time

from dsa_mq.connection import Connection

def my_callback(message):
    last_update = time.time()
    print "Got work item at %s" % last_update
    print message

conf = {
    'rabbit_userid': 'my_user',
    'rabbit_password': 'my_password',
    'rabbit_virtual_host': 'dsa',
    'rabbit_hosts': ['pubsub02.debian.org', 'pubsub01.debian.org'],
    'use_ssl': False
}

conn = Connection(conf=conf)
conn.declare_fanout_consumer(queue='my_user', callback=my_callback)

try:
    conn.consume()
except KeyboardInterrupt:
    sys.exit(0)
finally:
    conn.close()
