#!/usr/bin/python
import logging
import sys
import time

from dsa_mq.connection import Connection

FORMAT = "%(asctime)-15s %(message)s"
logging.basicConfig(format=FORMAT, level=logging.DEBUG)

LOG = logging.getLogger(__name__)

def my_callback(message):
    last_update = time.time()
    LOG.info("Got work item at %s" % last_update)
    LOG.info(message)

conf = {
    'rabbit_userid': 'my_test_user',
    'rabbit_password': 'XXXX',
    'rabbit_virtual_host': 'vhost',
    'rabbit_hosts': ['pubsub02.debian.org', 'pubsub01.debian.org'],
    'use_ssl': False
}

conn = Connection(conf=conf)
conn.declare_topic_consumer('dsa.git.mail',
                            callback=my_callback,
                            queue_name='my_queue',
                            exchange_name='dsa',
                            ack_on_error=False)

try:
    conn.consume()
except KeyboardInterrupt:
    sys.exit(0)
finally:
    conn.close()
