#!/usr/bin/python

import logging
import sys
import time

from dsa_mq.connection import Connection

FORMAT = "%(asctime)-15s %(message)s"
logging.basicConfig(format=FORMAT, level=logging.DEBUG)

LOG = logging.getLogger(__name__)

conf = {
    'rabbit_userid': 'my_user',
    'rabbit_password': 'my_password',
    'rabbit_virtual_host': 'dsa',
    'rabbit_hosts': ['pubsub01.debian.org', 'pubsub02.debian.org'],
    'use_ssl': False
}

conn = Connection(conf=conf)

msg = {
    'newhead': 'HEAD',
    'updated': time.time()
}

error = 0
try:
    conn.fanout_send('mail', msg)
except Exception, e:
    LOG.error("Error sending: %s" % e)
    error = 1
finally:
    conn.close()

sys.exit(error)
